# -*- coding: utf-8 -*-
"""NewsBot_Train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AeiMQOImvpCd3kiddN87zUDloCeKXzra
"""

import json
import pandas as pd
import spacy
import joblib
import string
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report

#Load JSON Dataset

file = "/content/News_Category_Dataset_v3.json"

data = []
with open(file, 'r') as f:
    for line in f:
        data.append(json.loads(line))

df = pd.DataFrame(data)
df.head()

#1. Keep only these categories: TECHNO, ENTERTAINMENT, POLITICS, BUSINESS.

selected_categories = ["TECH", "ENTERTAINMENT", "POLITICS", "BUSINESS"]

df = df[df["category"].isin(selected_categories)]
df["category"].value_counts()
df.head()

#2. Load spaCy’s English model without unnecessary components.

nlp = spacy.load("en_core_web_sm", disable=["parser", "ner"])
nlp

#3. Write a function to preprocess headlines: lowercase, remove stopwords,punctuation, and lemmatize.
def preprocess_headline(text):
    doc = nlp(text.lower())
    tokens = [
        token.lemma_
        for token in doc
        if token.is_alpha and not token.is_stop
    ]
    return " ".join(tokens)

#4. Apply preprocessing to all headlines.

df["clean_text"] = df["headline"].apply(preprocess_headline)

# 5. Convert text into numeric vectors using CountVectorizer with unigrams and bigrams
# 6.Limit the vocabulary size to 5000 features; explain why

vectorizer = CountVectorizer(ngram_range=(1, 2),max_features=5000)
x = vectorizer.fit_transform(df['clean_text'])  # ✅ IMPORTANT

#7. Create feature matrix x and label vector y.
#x = vectorizer.fit_transform(df["clean_text"])
y = df["category"]

# Save AFTER fitting
#joblib.dump(vectorizer, open("vectorizer.pkl", "wb"))

joblib.dump(vectorizer,"vectorizer_model.pkl")
print("Save vectorizer model........")

print("X shape:", x.shape)
print("y shape:", y.shape)

#8. Split data into training and test sets with balanced categories.

x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.2,stratify=y,random_state=42)

x_train.shape, x_test.shape, y_train.shape, y_test.shape

#9. Train Logistic Regression model with enough iterations.

log_model = LogisticRegression(max_iter=200)
log_model.fit(x_train, y_train)

joblib.dump(log_model, "logistic_model.pkl")
print("save logistic regression model......")

#10. Test the model and report accuracy.

y_pred = log_model.predict(x_test)
#accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

#11. Build a function to predict categories for new headlines.
def predict_category(headline):
    # 1. Preprocess the headline
    clean_text = preprocess_headline(headline)

    # 2. Vectorize the text
    text_vector = vectorizer.transform([clean_text])

    # 3. Predict category
    prediction = log_model.predict(text_vector)
    return prediction[0]

print(predict_category("Apple launches new AI powered iPhone"))

print(predict_category("Government passes new economic reform bill"))

#12. Create a Chabot that takes user input and predicts the category until user types 'quit' or 'exit’.
# CHATBOT

def chatbot():
    print("\n📰 News Category Chatbot")
    print("Type 'exit' or 'quit' to stop.\n")

    while True:
        user_input = input("You: ")

        if user_input.lower() in ["exit", "quit"]:
            print("Bot: Goodbye 👋")
            break

        processed = preprocess_headline(user_input)
        vector = vectorizer.transform([processed])
        prediction = log_model.predict(vector)[0]

        print(f"Bot: Category → {prediction}")

# Run chatbot
chatbot()

